backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

local_backend: true

collections:
  - name: "landing"
    label: "Landings (activités/visites)"
    folder: "content/landing"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string" }
      - { label: "Pays", name: "country", widget: "string", required: false }
      - { label: "Ville / Région", name: "city", widget: "string", required: false }
      - { label: "Description SEO", name: "seo_description", widget: "string", required: false }
      - { label: "Accroche / Intro", name: "intro", widget: "text", required: false }
      - { label: "Image de couverture", name: "hero_image", widget: "image", required: false }
      - label: "Points forts (3 max)"
        name: "highlights"
        widget: "list"
        required: false
        max: 3
        field: { label: "Texte", name: "text", widget: "string" }
      - { label: "Lien GetYourGuide", name: "gyg_offer_url", widget: "string", required: false, hint: "Colle ici ton lien partenaire." }
      - { label: "Texte du bouton GYG", name: "gyg_text", widget: "string", required: false, default: "Réserver via GetYourGuide" }
      - { label: "Disclaimer d’affiliation (optionnel)", name: "affiliate_disclaimer", widget: "text", required: false }
      - label: "Contenu (Markdown)"
        name: "body"
        widget: "markdown"
      - label: "FAQ"
        name: "faq"
        widget: "list"
        required: false
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Réponse", name: "answer", widget: "text" }
      - label: "Infos pratiques (puces)"
        name: "practical"
        widget: "list"
        required: false
        field: { label: "Texte", name: "text", widget: "string" }

  - name: "site"
    label: "Site (Home)"
    files:
      - name: "featured"
        label: "Landings en vedette (Home)"
        file: "content/landings.json"
        fields:
          - label: "Featured"
            name: "featured"
            widget: "list"
            label_singular: "Landing"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Résumé court", name: "summary", widget: "text", required: false }
              - { label: "Vignette (image)", name: "thumb", widget: "image", required: false }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug (URL)", name: "slug", widget: "string" }
      - { label: "Description SEO", name: "seo_description", widget: "string", required: false }
      - label: "Contenu"
        name: "body"
        widget: "markdown"
